app:
  container_name: loomio-app
  image: ${LOOMIO_CONTAINER_IMAGE}:${LOOMIO_CONTAINER_TAG}
  expose:
    - "3000"
  ports:
    - "3000:3000"
  env_file: ./env
  links:
    - db
  environment:
    - DATABASE_URL=postgresql://postgres:password@db/loomio_production
  volumes:
    - ./client:/loomio/public/client
    - ./uploads:/loomio/public/system
    - ./files:/loomio/public/files
    - ./plugins:/loomio/plugins/docker
    - ./import:/import

worker:
  container_name: loomio-worker
  image: ${LOOMIO_CONTAINER_IMAGE}:${LOOMIO_CONTAINER_TAG}
  env_file: ./env
  links:
    - db
  environment:
    - DATABASE_URL=postgresql://postgres:password@db/loomio_production
    - TASK=worker
  volumes:
    - ./client:/loomio/public/client
    - ./uploads:/loomio/public/system
    - ./files:/loomio/public/files
    - ./plugins:/loomio/plugins/docker

db:
  container_name: loomio-db
  image: postgres:${POSTGRES_CONTAINER_TAG}
  volumes:
    - ./pgdata:/pgdata
    - ./pgdumps:/pgdumps
  environment:
   - POSTGRES_PASSWORD=password
   - PGDATA=/pgdata

mailin:
  container_name: loomio-mailin
  image: ${MAILIN_CONTAINER_IMAGE}:${MAILIN_CONTAINER_TAG}
  links:
    - app
  environment:
    - WEBHOOK_URL=http://app:3000/email_processor/
